---
- name: Configure sysctl
  ansible.posix.sysctl:
    name: "{{item.name}}"
    value: '{{item.value}}'
  with_items:
    - { name: net.ipv4.ip_forward, value: 0 }
    - { name: net.ipv4.tcp_syncookies, value: 1 }
    - { name: net.ipv4.tcp_synack_retries, value: 5 }
    - { name: net.ipv4.conf.all.rp_filter, value: 1 }
    - { name: net.ipv4.conf.default.rp_filter, value: 1 }
    - { name: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 }
    - { name: kernel.panic, value: 10 }
    - { name: net.ipv4.icmp_ignore_bogus_error_responses, value: 1 }
    - { name: net.ipv4.ip_local_port_range, value: "1024 65535" }
    - { name: net.ipv4.tcp_fastopen, value: 3 }
    - { name: net.ipv4.tcp_keepalive_time, value: 600 }
    - { name: net.ipv4.tcp_keepalive_probes, value: 5 }
    - { name: net.ipv4.tcp_keepalive_intvl, value: 15 }
    - { name: vm.swappiness, value: 10 }
    - { name: fs.file-max, value: 2097152 }
    - { name: kernel.printk, value: "4 4 1 7" }
