---
- name: Create groups for users
  ansible.builtin.group:
    name: "{{item}}"
    state: present
  loop:
    - admins
    - users

- name: Create users
  ansible.builtin.user:
    name: "{{item.client_name}}"
    shell: /bin/bash/
    groups: users
    append: yes
    home: "/home/{{item.home_dir}}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  with_items:
    - {client_name: admin, home_dir: admin}
    - {client_name: user, home_dir: user}

- name: Set maximum expiration date for password
  ansible.builtin.user:
    name: user
    password_expire_max: 30

- name: Set number of warning days for password expiration
  ansible.builtin.user:
    name: user
    password_expire_warn: 20
