---
- name: Add key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present

- name: Update apt
  ansible.builtin.apt:
    update_cache: yes

- name: Install postgresql
  ansible.builtin.apt:
    name: postgresql-16
    state: present

- name: Check PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: true

- name: Set password for the postgres user
  become: true
  become_user: postgres
  ansible.builtin.command: >
    psql -c "ALTER USER postgres PASSWORD '{{ POSTGRES_PASS }}';"

- name: Change config
  ansible.builtin.blockinfile:
    path: /etc/postgresql/16/main/postgresql.conf
    append_newline: true
    prepend_newline: true
    block: |
      listen_addresses = '*'

- name: Change hba config
  ansible.builtin.blockinfile:
    path: /etc/postgresql/16/main/pg_hba.conf
    append_newline: true
    prepend_newline: true
    block: |
      host all all 0.0.0.0/0 md5

- name: Restart Postgresql
  service:
    name: postgresql
    state: restarted
